### ISSUE TITLE
Getting a strncpy error

### ISSUE THREAD

**Issue by starxfighter** [segmentio/aws-okta#104]
Upon issuing the go get github.com/segmentio/aws-okta command the software starts downloading and installing the package. The installation errors out with the following error message:

$ go get github.com/segmentio/aws-okta                                           
# github.com/marshallbrekka/go-u2fhost/vendor/github.com/marshallbrekka/go.hid   
hid_windows.c: In function 'hid_enumerate':                                      
hid_windows.c:423:5: warning: 'strncpy' specified bound depends on the length of  the source argument [-Wstringop-overflow=]                                           
strncpy(cur_dev->path, str, len+1);                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          
hid_windows.c:421:11: note: length computed here                                      
len = strlen(str);                                                                     
^~~~~~~~~~~

This error prevents aws-okta from being completely installed.

**Comment by nickatsegment** [comment]
Are you installing on Windows?

**Comment by starxfighter** [comment]
Shoot...sorry I forgot to add that. The machine is a windows 10  64-bit. I also have the latest version of Go installed. I also have the latest version of MinGW64 installed. Installation of Go and MinGW64 has been tested and verified. Path variable is pointing to all of the relevant bin locations.

**Comment by michaelreiser** [comment]
I getting this too.

**Comment by nickatsegment** [comment]
@devonbleak I know you folks use Windows: are you getting this error as well? Any advice?

**Comment by devonbleak** [comment]
Can confirm I had one report of this with mingw64 on Win10.  I use win-builds gcc and haven't run into it myself.

**Comment by devonbleak** [comment]
Submitted #118 that documents the existence of an issue with mingw-w64 gcc

**Comment by dave-tucker** [comment]
I think this should still be open as the warning is still present:

Windows Version
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```

GCC Version
```
$ gcc --version
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Warning
```
hid_windows.c: In function 'hid_enumerate':
hid_windows.c:423:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncpy(cur_dev->path, str, len+1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hid_windows.c:421:11: note: length computed here
     len = strlen(str);
           ^~~~~~~~~~~
```

**Comment by nickatsegment** [comment]
@dave-tucker What's the impact for you? Is it just annoying? Or does it prevent a build?

Seems like it's got the potential to be a security bug.

Frankly my ability to dive into a HID library written in C for Windows is pretty limited. I wouldn't expect this to get fixed any time soon.

**Comment by dave-tucker** [comment]
It's more concerning that annoying - especially as it's used to interact with USB security devices.
FWIW, I already took a look at fixing it... The trail of breadcrumbs...

- https://github.com/marshallbrekka/go-u2fhost
- https://github.com/marshallbrekka/go.hid
- https://github.com/GeertJohan/go.hid

Led to finding that `go.hid` is depreacted and doesn't work on Go 1.6+🤷‍♂ 
https://github.com/marshallbrekka/go-u2fhost/issues/4 is open to migrate to a newer HID library.
I'd guess that would need to be fixed before it could be picked up here.

**Comment by nickatsegment** [comment]
Ha, looks like our very own @alberts has been here before https://github.com/marshallbrekka/go-u2fhost/pull/3#issuecomment-410938489. Seems like these libs are all a little under-maintained. Seems like we should fork.

**Comment by canoztokmak** [comment]
this error still happens when trying to execute `go get github.com/segmentio/aws-okta`.

**Comment by nickatsegment** [comment]
Looks like https://github.com/marshallbrekka/go-u2fhost/issues/4 got fixed by https://github.com/marshallbrekka/go-u2fhost/issues/5, so maybe this error goes away. If a Windows user can get a build using this updated version of go-u2fhost tested, I'd be willing to accept a PR.
