### ISSUE TITLE
Option to configure default MFA

### ISSUE THREAD

**Issue by manishtomar** [segmentio/aws-okta#110]
The tool asks to choose MFA when running every-time:
```
INFO[0002] Requesting MFA. Please complete two-factor authentication with your second device
INFO[0002] Select a MFA from the following list
INFO[0002] 0: OKTA (push)
INFO[0002] 1: OKTA (token:software:totp)
```
And I always end up choosing the same option. It will be nice to provide this option in configuration file to avoid selecting the same option every time.

**Comment by nickatsegment** [comment]
Duplicates https://github.com/segmentio/aws-okta/pull/108? Can reopen if I'm misunderstanding.
