### ISSUE TITLE
Constantly being asked for pasphrase

### ISSUE THREAD

**Issue by kiranrajendran** [segmentio/aws-okta#112]
I have added an OKTA provider and user/pass details and can run aws cli commands.  I am being prompted for my passphrase every single aws command.

Running Ubuntu 18.04 using pre-built binary.

Is there a way to disable the passphrase entirely? If I leave it blank, I am prompted for the passphrase and have to hit Enter 3 times before it executes the command.

**Comment by nickatsegment** [comment]
Are you using the `--backend` option? If not, if you do `aws-okta add --help` it should give you a list of the backends available on your system. It sounds like you're using `file` (the fallback) which would exhibit the behaviour you're seeing

**Comment by nickatsegment** [comment]
Looks like `pass` is not available in our vendored copy of 99designs/keyring. Did you really want to use `pass`? A brief reading says it uses GPG to encrypt, which means passphrases or an agent, kicking the can down the road. 

What about `secret-service`? My understanding is that it's just an interface to GNOME or KDE secrets, which are a much more friend UI IMO.
