### ISSUE TITLE
Debug with VSCode

### ISSUE THREAD

**Issue by rv-dtomaz** [segmentio/aws-okta#120]
Is there any way to start debugging in VS Code with aws-okta ?

**Comment by nickatsegment** [comment]
I know @Fauzzy uses VS Code. Not sure about debugging though.

**Comment by rv-dtomaz** [comment]
@nickatsegment Thanks for your reply.
I figure out a way to do that. Actually I am creating a task to automate.
Basically I execute aws-okta exec [profile] -- env
So I am able to get secret key, acesstoken, etc and set to Env before start debug.

I know that is not the best way, but it is working fine.
