### ISSUE TITLE
Session expires during terraform execution

### ISSUE THREAD

**Issue by IngussNeilands** [segmentio/aws-okta#123]
This is feature request.

We use aws-okta with terrafom and when execution takes longer time that left on session - terraform execution fails. 

Please add a configurable parameter `AWS_SESSION_MINIMUM_TTL_TIME` = 15 minutes
And if its less that specified - that would force re-login

it would guarantee that session is valid whole execution time.

**Comment by nickatsegment** [comment]
Yeah, that'd be cool. We'd require some ability to query AWS for the token expiry time, which I assume exists but don't know off the top of my head.

**Comment by devonbleak** [comment]
@nickatsegment no such API call currently :-(

In terms of the issue here I think it's getting at the same thing I'm describing in #105 with the cached creds being returned when source profile == target profile.
