### ISSUE TITLE
improve error message for changed password?

### ISSUE THREAD

**Issue by bazzargh** [segmentio/aws-okta#127]
If you change your password in okta, authentication fails here:
https://github.com/segmentio/aws-okta/blob/e49af049b3a189faea558501d61450cfa0f3fae0/lib/okta.go#L166

...this is expected, but we're we're in a maze of authentication failures (session tokens etc). It'd be nice to indicate that this one is easy to fix: "If your password has changed, run `aws-okta add` again.", or perhaps "Invalid credentials, use `aws-okta add` to change them." - to cover more scenarios.

**Comment by nickatsegment** [comment]
Yep, that'd be cool. I don't know if we can detect the difference between your password having changed and other non-network errors, like your user being deleted. But we could probably offer suggestions.
