### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by andreebrazeau** [segmentio/aws-okta#128]
I am unable to login using a proxy: 
```➜  ~ aws-okta add --debug
Okta organization: Blah
Okta region ([us], emea, preview):
Okta domain [us.okta.com]:
Okta username: <my username> 
Okta password:

DEBU[0016] Step: 1
DEBU[0076] Failed to validate credentials: Failed to authenticate with okta: &url.Error{Op:"Post", URL:"https://FutureAdvisor.okta.com/api/v1/authn", Err:(*http.httpError)(0xc00000d200)}
Failed to validate credentials```

**Comment by nickatsegment** [comment]
Yeah, that error message isn't very good. Are you sure the proxy is the one breaking things? Does this work if there's no proxy?

**Comment by devonbleak** [comment]
@andreebrazeau what release are you on?

#115 should have this resolved in master but doesn't look like we've had a release since it was merged.

**Comment by andreebrazeau** [comment]
@nickatsegment I can try on my personal computer tonight doesn't doesn't need a proxy. 

@devonbleak I installed it from brew version `v0.19.4`.

**Comment by vivianho** [comment]
In an effort to try to trace HTTP requests via Charles proxy, I also get the same error as original post (on master)

**Comment by nickatsegment** [comment]
@vivianho 	I was doing some MITMing myself just a few days ago https://github.com/segmentio/aws-okta/pull/134. Seemed to work ok. Maybe your cached creds in the keychain are having an effect?
