### ISSUE TITLE
Okta session cookie expire

### ISSUE THREAD

**Issue by simonbacon** [segmentio/aws-okta#138]
Where do you set the expire time for "okta session cookie" ?  Does this come directly from okta?

It does not seem to respect our okta aws app session length at the moment,  I can see the profile session cookie times out after 60 minutes but it then just creates a new cookie without auth as the okta session cookie is still available.  If i delete the okta session cookie then i have to reauth after the 60 minutes

**Comment by nickatsegment** [comment]
Yep, pretty sure it's an admin knob. Took me a minute to [find it buried in this forum thread](https://support.okta.com/help/s/question/0D50Z00008G7VJo/adjusting-the-session-timeout-for-okta).

![image](https://user-images.githubusercontent.com/40582825/55501981-77b74900-5600-11e9-8068-4363ab31f539.png)
