### ISSUE TITLE
Support reading MFA code from an environment variable

### ISSUE THREAD

**Issue by jacobwgillespie** [segmentio/aws-okta#140]
It would be very useful from an automation standpoint if you could pass the value of an MFA code via an environment variable, say `AWS_OKTA_MFA_CODE`.  This would allow running another script that generated that TOTP code, vs needing it to be typed, something like:

```bash
$ AWS_OKTA_MFA_CODE="$(get_totp_code)" aws-okta exec <profile> -- <command>
```

**Comment by nickatsegment** [comment]
That's an interesting idea.

In the meantime, I bet you could whip something up with `expect`.

**Comment by jaredm4** [comment]
Came here to post the same request. Use case for myself is my password manager (BitWarden in this case) manages my mfa for majority of my sites. You can access the totp code from the [bitwarden-cli](https://www.npmjs.com/package/@bitwarden/cli), so I could save a step by scripting that prior to running the aws-okta command.

```AWS_OKTA_MFA_CODE="$(bw get totp 'Name or Id of Okta Item')" aws-okta exec ...```

Yeah, `expect` might provide a stop-gap in the meantime.
