### ISSUE TITLE
Support for exporting credentials

### ISSUE THREAD

**Issue by marcincuber** [segmentio/aws-okta#141]
Temporary credentials exported through environment variables;
```
$AWS_ACCESS_KEY_ID
$AWS_SECRET_ACCESS_KEY
$AWS_SECURITY_TOKEN
$AWS_SESSION_TOKEN
```
This will allow to use aws cli directly.
Possible to implement?

**Comment by nickatsegment** [comment]
Easiest thing to do is exec a subshell:

```
aws-okta exec profile -- bash
```

Or here's a hack to get the vars into the current shell
```
source <(aws-okta exec profile -- sh -c set | grep \^AWS )
```

I'd say that's simple enough that we don't need an explicit feature.
