### ISSUE TITLE
auto completion

### ISSUE THREAD

**Issue by marcincuber** [segmentio/aws-okta#142]
Is it possible to have auto completion when running;
```
aws-okta exec <profile> -- aws [TAB]
```

What would be the advised way of achieving that because aws cli itself already contains auto completion?

**Comment by FernandoMiguel** [comment]
@marcincuber 
aws-shell ?

**Comment by Darkflib** [comment]
`complete -C '/usr/local/bin/aws_completer' aws-okta
`
seems to work
![image](https://user-images.githubusercontent.com/101405/55624563-43798f00-579e-11e9-9bf8-c20b5147d10b.png)

**Comment by marcincuber** [comment]
looks good, sorted
