### ISSUE TITLE
Support webauthn MFA factor

### ISSUE THREAD

**Issue by sharpone74** [segmentio/aws-okta#158]
Looks like webauthn (yubikey 5c nano in this case) isn't supported. It would be great if it was.

```DEBU[0021] Step: 1
DEBU[0022] Step: 2
INFO[0022] Requesting MFA. Please complete two-factor authentication with your second device
DEBU[0022] 00uMrQE7-7jbCWJZz61wCH5d4PKf7V8YVp2IgMb0S4
DEBU[0022] Failed to validate credentials: factor webauthn not supported
Failed to validate credentials```

**Comment by nickatsegment** [comment]
I don't have access to a webauthn device here, so don't look at me :D Happy to accept a PR.

**Comment by sharpone74** [comment]
How about if I buy you one? ;)

**Comment by nickatsegment** [comment]
> How about if I buy you one? ;)

Haha, yeah, I can't really do that; I answer only to the crystalline entity that runs Segment.

**Comment by smiller171** [comment]
@nicgrayson If you're running on a Mac you have a WebAuthn device in the form of TouchID in Chrome

**Comment by smiller171** [comment]
https://www.yubico.com/product/security-key-by-yubico

**Comment by nickatsegment** [comment]
Well I actually bought a Yubikey 5c myself. I believe this would give us TouchID support as well, which would be super cool.

That said, there are no plans to implement this as yet. Happy to accept a PR though, and I can even test it now

**Comment by smiller171** [comment]
> I believe this would give us TouchID support as well

Right now I'm pretty sure only Chrome can use TouchID for WebAuthn, so you'd need to open a browser for the auth request.

**Comment by smiller171** [comment]
Even if it's not being tackled right now, I think it makes sense to keep this issue open

**Comment by bennumo** [comment]
Yeah, I'm happy to buy you one as well!  We're looking to shift from YubiKey + Seedfile to the U2F / WebAuthN implementation in Okta.  For us, this would help us to manage the growing list of YubiKeys we have.  It's getting difficult to manage seed files at scale.

**Comment by nickatsegment** [comment]
@bennumo fair enough, but like I said, no plans to implement this by maintainers at present. PRs encouraged (after #236 is lifted)

**Comment by smiller171** [comment]
I really don't like this definition of closed personally. I'm more in favor of a label indicating that an issue is low-priority but that PRs are welcome

**Comment by nickatsegment** [comment]
https://github.com/segmentio/aws-okta/issues/278
