### ISSUE TITLE
Support Hub + Spoke Setup

### ISSUE THREAD

**Issue by msvechla** [segmentio/aws-okta#159]
Hi, 
we are using a fork of your tool since more than a year now, thanks a lot!

We recently moved to an okta org2org / hub and spoke setup, where the AWS applications are now only configured in the spoke.

Do you have any idea what would be necessary to make aws-okta work in this setup?

What I already tried:

Get the `onetimetoken` via login from the hub and then using the hub domain for `Step 3`:
- here I get the error message, that the AWS app is not assigned to me

Setting the aws_saml_url to the okta org2org app link from the hub and appending a `fromURI=destinationAWSAppLinkInSpoke` as query parameter (as described here: https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/24#issuecomment-362130450) 
- here I get `Role 'x' not authorized by Okta.  Contact Okta admin to make sure that the AWS app is configured properly.`

Do you have any suggestions on how to make this work? As we are maintaining a fork anyways, hints on what we would need to adjust would also be very welcome.

Thanks for your support!

**Comment by nickatsegment** [comment]
Yikes! Unfortunately I'm not familiar with that setup. I'll ask around, but I wouldn't hold your breath :)

**Comment by msvechla** [comment]
Thanks a lot! Any hint would be greatly appreciated.
