### ISSUE TITLE
Support local development server

### ISSUE THREAD

**Issue by joshma** [segmentio/aws-okta#164]
I'm wondering if anyone has been able to get aws-okta running for a local development server. Ideally:

1. We can auth into an dev AWS account with a running e.g. Python process
2. The Python process is a web server, and it can e.g. download a file from S3
3. The AWS creds will need to be rotated periodically, since they expire - similar to how an EC2 instance profile works

I think there's a way to do this with aws-vault, where it'll run a local EC2 instance metadata server. Any chance folks already use aws-okta for this?

**Comment by nickatsegment** [comment]
I can't think of any easy way to deal with the expiring creds thing. But the metadata server sounds like a pretty dang good idea.

**Comment by joshma** [comment]
Darn - I'm guessing that this just isn't a common workflow @ Segment then? Is everything just run in the foreground?

**Comment by nickatsegment** [comment]
Yep, we tend to do `aws-okta exec profile -- server` and deal with the creds expiring. If we need something longer running, we get actual IAM creds created.

When you say "local development server", do you mean running on an actual server?

**Comment by joshma** [comment]
I mean a local Python/Flask process (and really, a broader set of processes that form the full environment) - so we use docker-compose, and we'll `docker-compose up` a web server + a task worker + a few other processes.

So we won't run each one in the foreground, and maybe we could run each one in aws-okta and restart it periodically. And there's the complication in aws-okta running in mac-land and us needing these creds in Docker-land...

**Comment by nickatsegment** [comment]
We do `aws-okta exec profile -- docker-compose up`, and then in the `docker-compose.yml` file, [if you have env vars without values, they will be passed through from the calling environment](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers). It's not ideal, but it gets the job done.

**Comment by joshma** [comment]
Ah...interesting. Thanks @nickatsegment - I'll close this out for now, appreciate the datapoints.
