### ISSUE TITLE
Custom Error Message for App Access

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/aws-okta#169]
The most common question we get from users is what to do when they encounter this error:

https://github.com/segmentio/aws-okta/blob/474c56b95a79486fb76417fcf47c20b0ca9ee542/lib/okta.go#L524-L526

Perhaps we should make it customizable (either through config or at compile time) such that we can include more specific instructions like who to email for access?

**Comment by nickatsegment** [comment]
Yep good idea.

Putting UI messages in lib-level errors is probably a bad idea. We should detect this error in the CLI, and then present it differently.
