### ISSUE TITLE
login: Allow user to specify a browser path

### ISSUE THREAD

**Issue by otterley** [segmentio/aws-okta#17]
Sometimes I like to use multiple browsers for logging into AWS (for example, when I want to compare two different environments, like prod and stage).  

It would be useful to be able to specify that I'd like to log in via Safari (which is not my default browser) instead of Chrome for a particular session.  I'm an OS X user.

**Comment by ejcx** [comment]
@otterley `aws-okta` is just using https://github.com/skratchdot/open-golang/, which is wrapper around `open`.

This would be pretty major surgery on the `login` subcommand.

**Comment by dfuentes** [comment]
The workaround [here](https://github.com/segmentio/aws-okta/pull/29) has been merged, that may work for your use case

**Comment by otterley** [comment]
Good enough, thanks!
