### ISSUE TITLE
Support pass backend

### ISSUE THREAD

**Issue by ryan-dyer** [segmentio/aws-okta#170]
Can we get support for the pass backend?  As I run in WSL2, this is the only keyring I've found that works for me.  aws-vault has been supporting this backend for a while now.

**Comment by nickatsegment** [comment]
Yep, seems like we just need to upgrade keyring

**Comment by ryan-dyer** [comment]
When can we get a release with this?

**Comment by nickatsegment** [comment]
@ryan-dyer 	Today!

**Comment by nickatsegment** [comment]
https://github.com/segmentio/aws-okta/releases/tag/v0.22.0
