### ISSUE TITLE
Session caching algorithm is incorrect?

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/aws-okta#179]
(I believe this to be true, but probably could stand to be double-checked.)

Sessions are cached based on their configuration, plus duration. This entails the following pathological series of events:

- get session 1h: cache miss; new session created, added to cache
- 59:59 min pass
- get session 1h: cache hit; old session reused, but only has 1s remaining until expiry, so the command fails

This is an extreme example, but can also lead to unexpected expiries. Say I want to run a command that I expect to take 30min to finish, and start it with a TTL of 1h, so it has a margin. `aws-okta` could give me a cached session with 5m left, and so my job terminates early.

**Comment by nickatsegment** [comment]
Maybe we could treat the user-specified TTL as a minimum TTL. Then, instead of the cache simply being a key lookup, it would need to be a search through cached sessions for that profile with a remaining time of anything greater than the requested time.

But maybe this is a bit surprising as well: you ask for a TTL of 1h, and could get a cached session that has 100h left on it. So maybe we need the user to specify a range? Or a margin of error?

**Comment by nickatsegment** [comment]
Boggs' suggestion is to only use the cache in a very short window, say 5m. The purpose of the cache is then just to avoid API rate limits (say when `exec`ing in a loop, not to be efficient about creds reuse.

**Comment by timoguin** [comment]
I feel like #190 is low hanging fruit that would help usability without having to modify this algorithm. As an initial improvement, we could output the remaining time to the user and/or export these values as environment variables.
