### ISSUE TITLE
No darwin binary for v0.21.0

### ISSUE THREAD

**Issue by olegburov** [segmentio/aws-okta#183]
Same as https://github.com/segmentio/aws-okta/issues/62. 

If I take a source and build it by myself, then I face another issue. The command `version` always returns `aws-okta-dev` instead of `aws-okta v0.21.0`. Now I don’t know which version I’m using. That walked me to another issue where my co-worked has one version and I have the other. His works fine, my doesn’t, because two different versions have different behaviour. For example see https://github.com/segmentio/aws-okta/issues/182

**Comment by nickatsegment** [comment]
How about using homebrew? It's got v0.21.0.

**Comment by olegburov** [comment]
@nickatsegment, as a workaround `brew install aws-okta` works. Thank you.
