### ISSUE TITLE
Issue with pass backend?

### ISSUE THREAD

**Issue by ryan-dyer** [segmentio/aws-okta#184]
Not sure if this is an issue with the pass backend or in my not having things configured correctly.

I have added my okta info via 
```aws-okta add -b pass```
with no issues but when attempting to exec:
```
 aws-okta -d exec okta-develop -- aws sts get-caller-identity
DEBU[0000] Parsing config file /home/rdyer/.aws/config
DEBU[0000] Using KrItemPerSessionStore
DEBU[0000] cache get `okta-develop session (39623335636434313162)`: miss (read error): The collection "awsvault" does not exist. Please add a key first
DEBU[0000] Using aws_saml_url from profile: okta
DEBU[0000] using okta provider
DEBU[0000] couldnt get okta creds from keyring: The collection "awsvault" does not exist. Please add a key first
getting creds via SAML: The collection "awsvault" does not exist. Please add a key first
```

Any ideas?  Thanks

**Comment by nickatsegment** [comment]
I'm pretty sure you'll need to pass `-b pass` to every command; that's not persisted anywhere.

**Comment by ryan-dyer** [comment]
That was it, thanks.  Theres currently not a way to add that to a config file as default?

**Comment by nickatsegment** [comment]
> That was it, thanks. Theres currently not a way to add that to a config file as default?

There isn't. Maybe a line in the config file would be a good feature. But in the meantime, I'd recommend a shell alias `alias aws-okta='aws-okta -b pass'`
