### ISSUE TITLE
Export session expiration timestamp as environment variable

### ISSUE THREAD

**Issue by timoguin** [segmentio/aws-okta#190]
Since the expiration timestamps from the STS sessions are available in the session cache, it would be nice to provide them as environment variables to the subshell, something like `AWS_SESSION_EXPIRATION` perhaps. It would also be nice if the CLI printed how much time was left in the session to stderr.

**Comment by nickatsegment** [comment]
Yep, those are good ideas. PRs appreciated :) 

Do you think `time remaining` is best? Or the datetime at which it expires?

Minor detail: I think maybe `AWS_OKTA_SESSION_EXPIRATION` is slightly better so as to not be confused with official `AWS_*` vars.

**Comment by timoguin** [comment]
`AWS_OKTA_SESSION_EXPIRATION` makes sense to me. I think `time remaining` will be the useful metric. Perhaps we should print both? Something like so: `Session expires in 15m at <timestamp>`.

**Comment by timoguin** [comment]
Also, should we print the same info for the Okta session on a separate line? I'm not sure if that would be too noisy or not. Maybe when debug is on?

**Comment by timoguin** [comment]
I'm also happy to submit a PR for this as soon as I have the time.

**Comment by timoguin** [comment]
Closed by #230. The `AWS_OKTA_SESSION_EXPIRATION` env variable is now exported as a Unix timestamp. (I'll probably create a follow-up to print this in local time.) Looks like the debug logs already print the remaining time for the session:

`DEBU[0000] Using session DGD3, expires in 11h6m12.402131s`
