### ISSUE TITLE
Spawn a subshell if no command is passed to exec

### ISSUE THREAD

**Issue by timoguin** [segmentio/aws-okta#191]
It would be nice if exec defaulted to spawning a subshell when no command is passed. This is how aws-vault behaves.

How I do this now: `aws-okta exec rolename -- $SHELL`

What I'd like to do: `aws-okta exec rolename`

aws-vault handles this by setting the default exec command to `$SHELL`:  https://github.com/99designs/aws-vault/blob/master/cli/exec.go#L86-L88

**Comment by nickatsegment** [comment]
That feels a little unintuitive to me, but I can see that if you're coming from `aws-vault` it'd be nice to be compatible. How about `aws-okta sh <profile>`?

Adding a shell alias/function would be pretty easy. 

Tell you what, if we can get 3 👍 on the issue, I'm totally willing to concede :)

**Comment by timoguin** [comment]
I'm happy to submit a PR for this as soon as I have the time.
