### ISSUE TITLE
role_arn in config breaks credentials file

### ISSUE THREAD

**Issue by apechimp** [segmentio/aws-okta#193]
I'm using `aws-okta` to populate my credentials file and then using the `AWS_PROFILE` environment variable to select which account I want to use. However, because `role_arn` is used by `aws-okta` to determine which role to assume via SAML, I get the following error when I use the aws cli.

```
Partial credentials found in assume-role, missing: source_profile or credential_source
```

I believe this is because the aws cli is attempting to get credentials the `role_arn` that was specified for okta to use. Since [`role_arn` is already reserved for use by the aws cli](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles), I think it would be good to use something like `okta.role_arn` to determine the role to assume via SAML and leave `role_arn` alone.

**Comment by bazimov** [comment]
I have resolved this by source_profile.
```
[profile my-profile]
role_arn=arn:aws:iam::XXXXX:role/my-role
role_session_name=my.username@example.com
source_profile=my-profile
```

**Comment by apechimp** [comment]
Works for me! Thanks!

**Comment by salarmehr-cbs** [comment]
doesn't work 
```
Infinite loop in credential configuration detected. Attempting to load from profile ...
```

**Comment by EdAyers** [comment]
Can we reopen this issue?
