### ISSUE TITLE
Add update command to modify profile credentials

### ISSUE THREAD

**Issue by timoguin** [segmentio/aws-okta#212]
Add a command that can update Okta credentials for an auth profile.

## Theoretical example

```
$ aws-okta update foo
Okta Username: foouser
Okta Password: ********

INFO[0013] Requesting MFA. Please complete two-factor authentication with your second device
INFO[0013] Select a MFA from the following list
INFO[0013] 0: GOOGLE (token:software:totp)
INFO[0013] 1: OKTA (sms)
Select MFA method: 0

Enter MFA Code: 111111

INFO[0024] Updated credentials for user foouser
```

## Command options

Here are some options I can think off:

```
aws-okta rotate foo
aws-okta add foo --update
aws-okta add foo --rotate
aws-okta update foo
```

**Comment by nickatsegment** [comment]
Can you show some theoretical examples?

**Comment by timoguin** [comment]
Updated the issue with some examples and options.

**Comment by nickatsegment** [comment]
Isn't this roughly equivalent to `source $(aws-okta env $AWS_OKTA_PROFILE)`? Or would this also force a session cache invalidation?

**Comment by timoguin** [comment]
Oh no, this would only be for updating the user's Okta credentials without having to remove and re-add them.

**Comment by nickatsegment** [comment]
> Oh no, this would only be for updating the user's Okta credentials without having to remove and re-add them.

Wow, I was clearly not reading. My bad.

Personally, I like `add --update` best.
