### ISSUE TITLE
[Parity] Support `exec --json` output like aws-vault

### ISSUE THREAD

**Issue by skyzyx** [segmentio/aws-okta#214]
I'm looking for a feature that provides parity with `aws-vault`. Specifically, I'm looking for an implementation of https://github.com/99designs/aws-vault/issues/299, which allows me to define a `credential_process` in my `~/.aws/config` file and can fetch the correct credentials when I use `--profile {PROFILE}` on the AWS CLI instead of always having to prefix with…

```bash
aws-okta exec default -- aws …
```

The AWS CLI documentation for this feature is here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

Thank you!

**Comment by nickatsegment** [comment]
Dupe of https://github.com/segmentio/aws-okta/issues/143?
