### ISSUE TITLE
pipeline: Makefile's `VERSION` is wrong if the commit is referred to by an older annotated tag and a unannotated tag.

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/aws-okta#222]
I retagged `v0.24.0` (annotated tag) with `v0.24.1` (unannotated tag) because the annotated tag broke some of our tooling. It turns out `git describe --tags` on a commit with an annotated and unannotated tag prefers the annotated tag. 

I believe this is because they sort by timestamp, and the timestamp of the unannotated tag is equivalent to the timestamp of the commit, which is older than that of the annotated tag. Pretty sure the annotated tag would *always* be older than the unannotated tag, since you can tag a commit that doesn't exist yet. :/

Probably we should just stick to one or the other. I was toying with annotated tags because it could be used to store a (generated) changelog, and would correctly show that I created it (not the committer in the case of a FF merge).

**Comment by nickatsegment** [comment]
I think we could fix this in the `Makefile` by using `$CIRCLE_TAG` if set. I just don't feel like testing this right now.

**Comment by switj** [comment]
@nickatsegment any update on this or help needed? `v0.24` still isn't available on bintray/brew

**Comment by nickatsegment** [comment]
> @nickatsegment any update on this or help needed? `v0.24` still isn't available on bintray/brew

Hm, yeah, looks like our CI for v0.24.1 didn't kick off for some reason.

You could submit a PR for v0.24.0 though; it is functionally equivalent. See https://github.com/Homebrew/homebrew-core/pull/44551. We have our own internal homebrew repo for aws-okta, so generally don't maintain upstream

**Comment by switj** [comment]
thanks, I'll put in a PR to homebrew when that binary is available. `0.24.0` also seems empty.

Thanks for pointing me the correct direction.

**Comment by nickatsegment** [comment]
Oh, looks like they just build off our source tarball anyway, which is built/generated by github automatically. So it doesn't matter that our CI failed to post binaries.
