### ISSUE TITLE
Add ability to switch role arns after authenticating

### ISSUE THREAD

**Issue by Shivang44** [segmentio/aws-okta#223]
https://github.com/segmentio/aws-okta/pull/165 added a really awesome feature: if a role_arn isn't specified, it will list available assumable roles and you can pick from the list.

Now the problem is that if you pick a role and authenticate, you can't rerun the command to authenticate to a different role. You're locked into that role arn you picked until it either expires or you delete the item manually from keychain. The only workaround I've found is to delete the state from the keychain, which doesn't work well when switching between roles multiple times per day. Without this feature the role arn picking isn't usable for us :/

Desired feature: Either a command called "unauthenticate" which deletes the state from the keychain (this would be challenging for the file backend probably because of requiring a password to decrypt), OR, even better, just allow you to repick a role everytime you run `aws-okta`. 

Thanks to everyone who already put so much work into this tool. It's awesome. If I get some free time I will definitely try to PR this in, but if anyone else wants to take a stab at this, this would be an awesome feature!

**Comment by Shivang44** [comment]
@nickatsegment @Fauzyy and other maintainers: If I was to try implement this feature, would you be willing to merge this upstream? Just want to get a feel for everyone's thoughts on this before going ahead and implementing.

**Comment by nickatsegment** [comment]
Yep, I think this is a good idea. I can think of a couple ways you might want to surface this to users:
- `exec --no-aws-session-cache`: don't read from or write to the session cache at all
- `exec --discard-session`: invalidate the session cache for that role before assuming (maybe this should reach out to AWS as well to close the session? not sure if this is a thing)
- `aws-okta discard-session <profile/role>`
Those names are a little wordy; I'm open to ideas to make them more concise.

From an implementation standpoint, this might be tricky. Currently the session cache interface uses [an opaque keying function (including a one-way hash)](https://github.com/segmentio/aws-okta/blob/00cceb3a5f980da5559b6365ec1cfd089b20cfe8/internal/sessioncache/key_orig.go) for `Put` and `Get`, so deleting items for a particular role would probably require making assumptions and parsing the key :/
