### ISSUE TITLE
How to force ignore/expire the session?

### ISSUE THREAD

**Issue by luzfcb** [segmentio/aws-okta#224]
Is there any way to force aws-okta to delete the current session and get a new one?
I have a strange error when using `aws-okta` + `pytest` + `boto3` + `iam`
For whatever reason I haven't been able to find out yet, the `boto3` raised this error:

```bash
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the SimulateCustomPolicy operation: Signature expired: 20190505T000000Z is now earlier than 20190925T121254Z (20190925T122754Z - 15 min.)
```

```bash
(project) luzfcb@fabio:~/project$ aws-okta -d exec foobar_aws_profile -- pytest tests/e2e/test_enforcer_django.py
DEBU[0000] Parsing config file /Users/luzfcb/.aws/config
DEBU[0000] Using KrItemPerSessionStore
DEBU[0000] cache get `sandbox session (24374530333337414541)`: hit
DEBU[0000] Using session DLZC, expires in 45m49.744341s

# ... other codes
    def _make_api_call(self, operation_name, api_params):
       # ... other codes
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id,
                operation_name=operation_name),
            http_response=http, parsed=parsed_response,
            model=operation_model, context=request_context
        )

        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the SimulateCustomPolicy operation: Signature expired: 20190505T000000Z is now earlier than 20190925T122705Z (20190925T124205Z - 15 min.)
```

My guess is somehow `aws-okta` use a previous (wrong) session from the local machine `aws-okta` session cache (if it exists).

**Comment by raxod502-plaid** [comment]
Did you ever find a solution to this problem?

**Comment by nickatsegment** [comment]
@raxod502-plaid as a workaround, you should just be able to delete the session cache keyring item(s). On macOS, this easy with the Keychain Access app. On other platforms/keyring backends, I don't know off the top of my head.

**Comment by raxod502-plaid** [comment]
I can confirm that this works. Note to future readers, if you are doing this to try and force changing which AWS IAM role is in use, you need to make sure that the AWS profile name you pass to `aws-okta` does **not** have `role_arn` set in `~/.aws/config`; otherwise, you will be prompted for an IAM role only nondeterministically, rather than every time.
