### ISSUE TITLE
aws-okta doesn't work with ap-east-1 region

### ISSUE THREAD

**Issue by kamil-szczygiel-dragon** [segmentio/aws-okta#225]
```
aws-okta exec x -- aws ec2 describe-instances --region ap-southeast-1
{
    "Reservations": []
}
```

```
aws-okta exec x -- aws ec2 describe-instances --region ap-east-1

An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
exit status 255
```

**Comment by kamil-szczygiel-dragon** [comment]
Actually this is related to aws-okta. After upgrading all deps it started to work.

**Comment by eculver** [comment]
Which version were you using? Does the latest version have the same behavior? We just released `v0.25.0` 4 days ago. Could you try with that version and report back?

**Comment by kamil-szczygiel-dragon** [comment]
```
Error: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid
        status code: 403, request id: 3009c0db-efe7-11e9-bd84-ed486c0fc78b
```

With 0.25.0.

**Comment by eculver** [comment]
As it turns out, this region, me-south-1 (Bahrain) and all future regions require them to be enabled in your AWS account before they are accessible. Once I enabled this region for an account that we own and waited a bit, things started working. Can you give this a shot?

More info here: https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/
> AWS is changing the default behavior for all new Regions going forward. For new AWS Regions, you will opt in to enable your account to operate in those Regions. This makes it easier for you to select the regions where you can create and manage AWS resources. To prepare for upcoming Region launches, we recommend that you validate the capability to enable and disable AWS Regions to ensure only approved IAM principals can enable and disable AWS Regions for your account.
