### ISSUE TITLE
ArchLinux install instructions

### ISSUE THREAD

**Issue by wsny** [segmentio/aws-okta#232]
I've added an AUR package to easily install this on ArchLinux. Updated the wiki here

https://github.com/wsny/aws-okta-wiki/blob/aur-pkgbuild/Installation.md

Let me know if you want control of the PKGBUILD on the AUR, I can add you as a maintainer so you can make changes/updates if needed.

https://aur.archlinux.org/packages/aws-okta-bin/

**Comment by nickatsegment** [comment]
Neat, [I added section in our wiki](https://github.com/segmentio/aws-okta/wiki/Installation/_compare/c83138fd91a1a752a9cb079ecb7f6ae854277aa7).

I personally don't have the bandwidth to maintain it, but will put a call out internally to see if any of our Arch users would be willing.

Thanks!

**Comment by wsny** [comment]
I'm "watching" releases here, so hopefully I'll notice them. It's a simple change to bump the version and sha, so I'll see I'll try to keep it up to date. AUR will let someone else take it over if I become unresponsive ;)
