### ISSUE TITLE
Please push package for Ubuntu 19.10 Eoan Ermine

### ISSUE THREAD

**Issue by diegs** [segmentio/aws-okta#233]
Ubuntu 19.10 Eoan Ermine was released on 10/17.

I believe someone needs to `package_cloud push` to make it available for eoan:

https://packagecloud.io/segment/aws-okta/

**Comment by nickatsegment** [comment]
https://packagecloud.io/segment/aws-okta/packages/ubuntu/eoan/aws-okta_0.26.3_amd64.deb

In the process, I realized we hadn't published anything to packagecloud since v0.20.x 😬 Fixed!
