### ISSUE TITLE
ATTENTION DEVS: moratorium on breaking changes until 2020-01-01

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/aws-okta#236]
https://github.com/segmentio/aws-okta/issues/234 entails a fairly involved refactor. I'm giving @switj and their team 2 weeks to get it done. During this time, to make the refactoring easier and to ensure it's comprehensive, we  should avoid making any big changes, especially to the API.

If we find we absolutely must, the change must be listed here so that it can be incorporated into #234.

Updated to 2020-01-01. This is taking longer than expected. I'm going to take over the refactor now though.

**Comment by ebabani** [comment]
@nickatsegment Mind if we get this small bugfix in? https://github.com/segmentio/aws-okta/pull/237

It makes the `exec -r` option work properly when switching between multiple roles.

**Comment by nickatsegment** [comment]
@ebabani Yep, I had a comment on that PR, but yes, sounds like it's worth making an exception for. Thanks for following procedure ✔️

**Comment by nickatsegment** [comment]
Merged https://github.com/segmentio/aws-okta/pull/245

**Comment by nickatsegment** [comment]
Merged https://github.com/segmentio/aws-okta/pull/244

**Comment by nickatsegment** [comment]
Merged https://github.com/segmentio/aws-okta/pull/255

**Comment by nickatsegment** [comment]
Merged https://github.com/segmentio/aws-okta/pull/260 and https://github.com/segmentio/aws-okta/pull/259

**Comment by nickatsegment** [comment]
https://github.com/segmentio/aws-okta/issues/278
