### ISSUE TITLE
improvement: Export session expiration timestamp env var as local time

### ISSUE THREAD

**Issue by timoguin** [segmentio/aws-okta#240]
Thanks to @douglaswth submitting #230, the `AWS_OKTA_SESSION_EXPIRATION` environment variable is currently exported in Unix time. I think it'd be more friendly to format the time to ISO 8601 by using `time.Time.Format(time.RFC3339)`.

**Comment by douglaswth** [comment]
I chose to implement it as Unix epoch seconds as that was the lowest common denominator between doing shell math and ease of date parsing across different `date` utilities (coreutils has the awesome `-d`/`--date` flag, but BSD `date` which I believe is what a Mac has only has the `-r` flag which only takes Unix epoch seconds`). Perhaps there could be a separate environment variable for a formatted value?

**Comment by nickatsegment** [comment]
@timoguin when you say "more friendly", you mean for humans or computers? I'm not sure I see a lot of value in making the env var more human-friendly
