### ISSUE TITLE
bug (build): Unable to build binaries on Mac OS X Sierra

### ISSUE THREAD

**Issue by timoguin** [segmentio/aws-okta#241]
I'm unable to build the latest binaries on OS X Sierra. I have tried building from `master` ([e5359b](https://github.com/segmentio/aws-okta/commit/e5359bb0f24f0e453aeb8afedafdaca822fa88b9)) as well as the latest stable release ([v0.26.3](https://github.com/segmentio/aws-okta/releases/tag/v0.26.3)). Both have the same result.

I get the following error when trying to run `make all`:
```
$ make all
GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -ldflags='-X "main.Version=v0.26.3-pre1-2-ge5359bb-dev"' -o dist/aws-okta-v0.26.3-pre1-2-ge5359bb-dev-linux-amd64
build github.com/segmentio/aws-okta: cannot load github.com/marshallbrekka/go.hid: no Go source files
make: *** [dist/aws-okta-v0.26.3-pre1-2-ge5359bb-dev-linux-amd64] Error 1
```

I'm running Go 1.13.3:

```
$ go version
go version go1.13.3 darwin/amd64
```

Any ideas?

**Comment by nickatsegment** [comment]
Right `make all` builds for all platforms, and I think the linux build needs some `libusb` headers to work IIRC.

You should probably just do `go build`.

(Admittedly our `Makefile` rules are a little weird.)
