### ISSUE TITLE
bug: distributed binary no longer works on alpine

### ISSUE THREAD

**Issue by osterman** [segmentio/aws-okta#246]
## what
Running on alpine (with `libc6-compat` and `libusb`) produces these errors:
```
Error relocating /packages/tmp/build.BDmoBI/src/aws-okta: __pthread_register_cancel: symbol not found
Error relocating /packages/tmp/build.BDmoBI/src/aws-okta: __pthread_unregister_cancel: symbol not found
```

Can't find workaround. Used to work on earlier versions.

**Comment by osterman** [comment]
Maybe distribute static binary? =)

**Comment by nickatsegment** [comment]
I'm assuming this is running in Docker? Maybe we should just publish a Docker image

**Comment by osterman** [comment]
@nickatsegment correct, however, we run it in our own "cloud automation shell" called [`geodesic`](https://github.com/cloudposse/geodesic). This allows us to version the tools for each environment and not orchestrate everything natively on a workstation.

Then we ship `aws-okta` as part of our alpine package repository: https://github.com/cloudposse/packages

Your Okta cli is *by far* the best one out there for Okta. Thanks for keeping an interface similar to `aws-vault` (very smart!)

If you were to publish an official Docker image, I am sure it would benefit many; however, it wouldn't help our situation as we cannot easily switch from alpine due to our MASSIVE investment in all the packages we support for devops/cloud automation.

**Comment by nickatsegment** [comment]
Gotcha.

Well, if you can figure out a way to build/run it properly for alpine, I'm happy to start distributing it. Not sure I have the bandwidth right now to figure it out. It's probably just `CGO_ENABLED=0`

**Comment by osterman** [comment]
@nickatsegment yes, `CGO_ENABLED=0` usually does it!
