### ISSUE TITLE
"exit status ###"

### ISSUE THREAD

**Issue by asottile** [segmentio/aws-okta#247]
I find it very strange that `aws-okta exec` prints this when the underlying command exits nonzero -- I haven't found another tool that acts like and so I find it a little strange

Is there a reason for this? Can it be factored out (it's more noise on things actually failing)?

**Comment by nickatsegment** [comment]
I think the intention was that you could differentiate between the exit code of the exec'd app vs the exit code of aws-okta itself. Not sure if this is used, or if aws-okta itself actually exits with any code other than 0 or 1
