### ISSUE TITLE
Add support for passwords with space character

### ISSUE THREAD

**Issue by etopeter** [segmentio/aws-okta#249]
Current code trims spaces from user password input. We would like to allow users to use passwords with space characters.

Code references:
https://github.com/segmentio/aws-okta/blob/fc734bb5a40d6f8c42743cf7654b5b88be533d70/lib/prompt.go#L27
https://github.com/segmentio/aws-okta/blob/fc734bb5a40d6f8c42743cf7654b5b88be533d70/lib/prompt.go#L34

**Comment by nickatsegment** [comment]
I'm not sure why it does that. But we're on hiatus now, so wontfix https://github.com/segmentio/aws-okta/issues/278
