### ISSUE TITLE
Missing support for AWS_SESSION_TTL and AWS_ASSUME_ROLE_TTL in env and write-to-credentials

### ISSUE THREAD

**Issue by chizou** [segmentio/aws-okta#252]
The options `env` and `write-to-credentials` don't seem to have the calls to `loadDurationFlagFromEnv` that the `exec` option seems to have. This is breaking some of our use cases. Can it be added to bring `env` and `write-to-credentials` on parity with `exec`?

**Comment by chizou** [comment]
They also seem to be lacking support for the `assume_role_ttl` option in the config file

**Comment by nickatsegment** [comment]
Wontfix https://github.com/segmentio/aws-okta/issues/278
