### ISSUE TITLE
cred-process outputs lines other than json breaking parsing by aws sdks

### ISSUE THREAD

**Issue by edulop91** [segmentio/aws-okta#253]
AWS SDKs capture the output of `cred-process` and expect it to be json formatted. Unfortunately, output such as 
```
INFO[0001] Requesting MFA. Please complete two-factor authentication with your second device 
INFO[0001] Sending Push Notification...
```
is incompatible with this scheme.

One possible solution is to allow users to configure aws-okta's log level

**Comment by nickatsegment** [comment]
Yeah, we need some output cleanup. I would argue that `INFO[0001] Requesting MFA. Please complete two-factor authentication with your second device` is not appropriately called a "log"; it's a UI message to the user. As such, maybe it should go to `stderr` since we're using `stdout` for data

**Comment by edulop91** [comment]
Sounds good! Should we by default redirect all logrus output to stderr? Or should we only do that for the creds-process command?

**Comment by jgadling** [comment]
Proposed fix:
https://github.com/segmentio/aws-okta/pull/260

**Comment by nickatsegment** [comment]
Should be fixed.
