### ISSUE TITLE
Authentication flow fails at Duo Push, unsure of cause

### ISSUE THREAD

**Issue by andrewrosezen** [segmentio/aws-okta#26]
I've set up an aws-okta profile, and can use Okta to log into the role it specifies normally. When I attempt to use aws-okta, it gets to the MFA portion, waits for 2-3 seconds, then fails without sending a push. From the Duo side, there are no corresponding failed MFA events. Is there anything else I can do track down what's going on?
```
$ aws-okta login profile-name -d
DEBU[0000] Parsing config file /Users/andrewr/.aws/config
DEBU[0000] using okta provider
DEBU[0000] Failed to reuse session token, starting flow from start
DEBU[0000] Step: 1
DEBU[0002] Step: 2
INFO[0002] Sending push notification...
DEBU[0002] Okta Factor ID: <looks right>

DEBU[0003] Host:api-23a196fe.duosecurity.com
Signature:<REDACTED>
StateToken:<REDACTED>

DEBU[0003] challenge u2f
Failed Duo challenge
```

**Comment by dfuentes** [comment]
That's certainly strange, not something I'm able to reproduce.  It could be some configuration issue within okta/duo specific to your setup.  Can you think of anything out of the ordinary with your configuration?

**Comment by michaelhood** [comment]
I have the same issue. The only difference in my log output is the addition of an INFO-level line just before the end:

```
DEBU[0007] challenge u2f
INFO[0007] Sending Push Notification...
Failed Duo challenge
```

**Comment by gregburek** [comment]
Investigating @michaelhood's report, I have been able to find that this specific error we are seeing is due to the DoAuth POST request to the Duo /frame/web/v1/auth endpoint returning 200 immediately, with no redirect. 

Looking at the okta iframe flow in chrome dev tools, there are two requests to /frame/web/v1/auth, the first of which returns 200 and the second returns 302. Did something change with this undocumented api endpoint?

**Comment by andrewrosezen** [comment]
@gregburek's PR fixed the issue for me, largely (I still had to adjust some policy settings Duo-side, but the auth attempts at least showed up in Duo's authentication log after building his branch locally).

My speculative guess is that it's related to our account being in the Duo Beyond tier, which lets you tack on some trust policies to the auth flow.

**Comment by dfuentes** [comment]
Interesting, I will try out the PR and see if it breaks anything with our Duo flow
