### ISSUE TITLE
Cannot update aws-okta on macOS Catalina

### ISSUE THREAD

**Issue by ravioactive** [segmentio/aws-okta#261]
15:55 $ go get -u github.com/segmentio/aws-okta
# github.com/segmentio/aws-okta/vendor/github.com/keybase/go-keychain
cgo-gcc-prolog:194:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here

**Comment by ravioactive** [comment]
I also tried to remove and re install aws-okta, and I got the same error. Now the binary shows the following error on running:
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize

**Comment by nickatsegment** [comment]
Pretty sure that's just a warning (that we nonetheless should address; will cut a ticket).

Can you install via homebrew instead?

**Comment by ravioactive** [comment]
Ok, works! Thank you.
