### ISSUE TITLE
Running with the Error While installing gcc using win-builds on windows 10

### ISSUE THREAD

**Issue by Naira16** [segmentio/aws-okta#263]
<img width="577" alt="Capture" src="https://user-images.githubusercontent.com/50852280/71022882-8fbbf380-20cf-11ea-9731-3007f538b568.PNG">

**Comment by Naira16** [comment]
Has anyone face this kind of Issue before?

**Comment by eculver** [comment]
I don't think any of the maintainers have used win-builds to install packages (I don't think any of us use Windows, actually). For starters, is this gcc related? How does aws-okta come in other than by virtue of it depending on gcc?

**Comment by Naira16** [comment]
https://github.com/segmentio/aws-okta/blob/master/docs/windows.md

i am following the above link

**Comment by nickatsegment** [comment]
That was contributed by a user. Maybe @devonbleak can help

**Comment by devonbleak** [comment]
I'd suggest taking it up with the win-builds team as the error appears to be something internal to that.  Unfortunately I'm not in a position to provide direct support for it.  In related news we've brought in a new developer @dkujawski to help sort out some of the pain points with the Windows builds with the goal of eliminating the need for the extra shared libraries, or at least providing something like a Windows installer that would include them.

**Comment by dkujawski** [comment]
While I can’t comment on the Win-builds issue directly, I have had some recent success in building a more portable Windows executable that does not rely on shared libraries.  

As a work around to requiring each Windows user to build from source, I have been looking at providing a Windows installer that contains an already built executable that is put in place for the user and will update the system path environment variable(s).  This does require a build machine to have all the necessary libraries installed, using Win-Builds.  

The default Go build process, with vendoring, results in an executable is dynamically linked to libraries that are expected to already be installed on the user’s machine (like libiconv).  This appears to be related to how the `govendor` process skips over non-Go libraries like those brought in via CGO as used in dependent libraries like [marshallbrekka/go-u2fhost](https://github.com/marshallbrekka/go-u2fhost) and [karalabe/hid](https://github.com/karalabe/hid). The current vendoring process is shallow and leaves them out.  See description and links here for more details: https://github.com/nomad-software/vend#why

I am seeing success with building an all-in-one executable after using a deeper vendoring tool like: https://github.com/nomad-software/vend.  

Here is my workflow:

Ensure that we get the latest updates from marshallbrekka/go-u2fhost to use the karalabe/hid library.

```
PS> go mod vendor
PS> go get github.com/marshallbrekka/go-u2fhost
```

Get the “deep” vend tool and run it on the root of segmentio/aws-okta

```
PS> go get github.com/nomad-software/vend
PS> vend
```

Now build the windows executable.

```
PS> go build -o dist/windows/aws-okta.exe -mod=vendor -ldflags="-X main.Version=v0.27.0-4"
```

This results in a more portable executable that is then able to be used on a Windows machine without the need to install the libraries that were previously required to be installed by the Win-builds process.

From there you can use any Windows packaging tool to build an installer script to take it from there.  I put together a basic `aws-okta-setup.exe` file using Inno Setup (http://www.jrsoftware.org/isinfo.php) to manage this for our internal install processes.

**Comment by Naira16** [comment]
Thank you So much Dev..

Will process as per your suggestion. Really appreciate your kind responce.
