### ISSUE TITLE
brew install aws-okta for macos is broken

### ISSUE THREAD

**Issue by limbalrings** [segmentio/aws-okta#267]
I ran `brew install aws-okta`

And then running `aws-okta` returns error "cannot execute binary file"

Installing the previous formula committed in brew fixed the issue.

**Comment by nickatsegment** [comment]
Yep, can repro.

Introduced in https://github.com/Homebrew/homebrew-core/commit/31868f8ff0b4d7aebe305c5acf7a5f28fa1103f0#diff-8987f2dd164c4087c93e950056dfccb4

**Comment by nickatsegment** [comment]
@limbalrings please report to homebrew. We don't maintain the formula. 

I'm not sure what's breaking. I was able to build locally with the same flags and the executable looks fine:

```
$ go build -ldflags '-s -w -X main.Version=v0.27.0' -trimpath -o aws-okta
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
$ ./aws-okta version
aws-okta v0.27.0
$ file aws-okta
aws-okta: Mach-O 64-bit executable x86_64
```

versus theirs, which starts with a bunch of null bytes:
```
$ xxd -a `which aws-okta` | head
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00002a70: ff20 476f 2062 7569 6c64 2049 443a 2022  . Go build ID: "
00002a80: 6c66 6375 6353 7274 5f62 7544 3561 7274  lfcucSrt_buD5art
00002a90: 6430 7a58 2f73 384d 396b 5546 7751 5571  d0zX/s8M9kUFwQUq
```

Maybe it's getting built for Linux somehow? Though I'd expect `file` to be able to detect that.

**Comment by nickatsegment** [comment]
As a workaround, you can build from source with:

```
brew install Homebrew/homebrew-core/aws-okta -s
```

And that appears to work fine for me.

**Comment by jamesacampbell** [comment]
I can confirm `brew install aws-okta` broken currently and the workaround mentioned by @nickatsegment works great for now.

**Comment by bazimov** [comment]
Created issue on homebrew side: https://github.com/Homebrew/homebrew-core/issues/48728
