### ISSUE TITLE
Add release for debian/buster

### ISSUE THREAD

**Issue by lingxiaoyang** [segmentio/aws-okta#274]
Currently, packagecloud is only offering debian/stretch and this leads to an installation failure following the [installation instructions](https://github.com/segmentio/aws-okta/wiki/Installation#debianubuntu-from-packagecloudio) on debian/buster.

debian/buster has been the backing environment for a number of standard Docker images, such as `python3.7`.

**Comment by nickatsegment** [comment]
FYI the DEBs are identical, so you can just download and install with `dpkg -i`. Of course you don't get automatic updates with that.

wontfix due to https://github.com/segmentio/aws-okta/issues/278
