### ISSUE TITLE
How can I prompt for password without a tty?

### ISSUE THREAD

**Issue by chizou** [segmentio/aws-okta#275]
When I ssh into a system and try to run aws-okta, it hangs for me because it prompts on the system's desktop to unlock the keyring instead of prompting in the SSH session. Is there some way to make it prompt in there instead of prompting on the desktop?

**Comment by nickatsegment** [comment]
You could try a different keyring backend. `pass` for example is just a wrapper around GPG, which has an infinite number of ways to prompt for your passphrase.

At Segment, we use SSH environment variable forwarding.
