### ISSUE TITLE
Okta MFA prompts with multiple options are not helpful

### ISSUE THREAD

**Issue by elementalvoid** [segmentio/aws-okta#28]
When configured with MFA the prompt from `aws-okta` is not helpful; it doesn't indicate which of several options is which "factor" (SMS vs. OTP vs. Push).

For example:
```
$ aws-okta exec dev -- aws sts get-caller-identity
DEBU[0000] Parsing config file /home/mklich/.aws/config
DEBU[0000] Using aws_saml_url from profile: dev
DEBU[0000] using okta provider
DEBU[0000] Failed to reuse session token, starting flow from start
DEBU[0000] Step: 1
DEBU[0001] Step: 2
INFO[0001] Requesting MFA
DEBU[0001] <<redacted>>
INFO[0001] Select a MFA from the following list
INFO[0001] 0: OKTA
INFO[0001] 1: OKTA
INFO[0001] 2: OKTA
Select MFA method: 0
DEBU[0006] Okta Factor ID: <<redacted>>
DEBU[0006] Okta Factor Type: token:software:totp
DEBU[0006] Token MFA
Enter MFA Code: 
```

There are three MFA options but you cannot tell which is which until you choose one; and then only when debug logging is enabled.

**Comment by elementalvoid** [comment]
This is the culprit for me: https://github.com/segmentio/aws-okta/blob/master/lib/okta.go#L174

And, fixing it for me is also very simple.
```go
log.Infof("%d: %s (%s)", i, f.Provider, f.FactorType)
```
But, I don't know what that will look like for 2FA provided by Duo or others.

Let me know if the "simple" fix is desired and I'll put up a PR!

**Comment by dfuentes** [comment]
Thanks for the report.  We use Duo solely, so didn't see this issue.  I've created a PR with your fix here https://github.com/segmentio/aws-okta/pull/33
