### ISSUE TITLE
DUO requires enabling "OtherOS" when using aws-okta

### ISSUE THREAD

**Issue by beiriannydd** [segmentio/aws-okta#282]
Hoping this meets the requirement of a straightforward bugfix.  Default user-agent string for Golang is simply "Golang-http-client/1.1" which is fine for many purposes, but Duo expect to see a an OS and Arch in parenthesis following it.  I wrote a library which solves this problem and makes the PR Into other apps a trivial matter.  I've only made the change to the duo.go code as this was the only place our corporate duo instance was blocking use of aws-okta.
Duo themselves have confirmed that the OS match for Mac is correct, I've asked them to review this PR and the library as well.

PR to follow.

**Comment by nickatsegment** [comment]
As mentioned in https://github.com/segmentio/aws-okta/pull/283, this feels more like a feature request to me. Sorry!
