### ISSUE TITLE
panic: runtime error: slice bounds out of range [308:282]

### ISSUE THREAD

**Issue by yzhang-flexera** [segmentio/aws-okta#289]
Hi,
I am using WSL and ubuntu environment. I followed instruction on https://github.com/segmentio/aws-okta to install aws-okta. After installation, when I tried to run aws-okta command, it gave me such error messages:
$ sudo aws-okta
panic: runtime error: slice bounds out of range [308:282]

goroutine 1 [running]:
github.com/godbus/dbus.getSessionBusPlatformAddress(0xa9916f, 0x18, 0x0, 0x0)
        /go/src/github.com/segmentio/aws-okta/vendor/github.com/godbus/dbus/conn_other.go:30 +0x299
github.com/godbus/dbus.getSessionBusAddress(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/segmentio/aws-okta/vendor/github.com/godbus/dbus/conn.go:96 +0xbd
github.com/godbus/dbus.SessionBusPrivate(0xc00005ce18, 0xc00009a690, 0xa92bbf)
        /go/src/github.com/segmentio/aws-okta/vendor/github.com/godbus/dbus/conn.go:101 +0x22
github.com/godbus/dbus.SessionBus(0x0, 0x0, 0x0)
        /go/src/github.com/segmentio/aws-okta/vendor/github.com/godbus/dbus/conn.go:73 +0xeb
github.com/99designs/keyring.init.1()
        /go/src/github.com/segmentio/aws-okta/vendor/github.com/99designs/keyring/kwallet.go:24 +0x51

Can you please suggest what is causing this error? I tried multiple times and still cannot get rid of it.

**Comment by cdeneen-peloton** [comment]
Hi,
You need to remove the x11-dbus package for it to work. This may prevent you from using GUI apps or if you go through with setting up and X11 server for WSL that might also fix the aws-okta problem. I haven't tested either situation.

`sudo apt-get remove dbus-x11`

**Comment by yzhang-flexera** [comment]
Thank you @cdeneen-peloton 
That fixed my issue.
