### ISSUE TITLE
aws-okta failed duo challenge

### ISSUE THREAD

**Issue by evanH13** [segmentio/aws-okta#295]
In our environment, we use Duo for 2fa. Two days ago, we ran into an issue where users were using the aws-okta tool, receiving the duo push, approving the push, but the tool would throw a 403 error state "Failed to validate credentials: Failed Duo challenge. Err: Prompt request failed: 403
Failed to validate credentials". The issue was resolved after upgrading the aws-okta tool. Now, however, we are running into the issue again. Is anyone else having the same problem?

**Comment by evanH13** [comment]
https://github.com/aws-okta/aws-okta/issues/9 

Any chance we can get this release made available?

**Comment by mikeborsuk-optimizely** [comment]
This was fixed again for me by PR #294 and is in release 1.0.4, have you tried that yet @evanH13?

**Comment by evanH13** [comment]
@mikeborsuk-optimizely I tried to upgrade via homebrew but I don't think release 1.0.4 is available yet.

**Comment by mikeborsuk-optimizely** [comment]
@evanH13 I just opened a PR for that version bump in homebrew, hopefully will get merged soon, in the mean time our team is using the 1.0.4 release directly from here and/or building from source to work around.
