### ISSUE TITLE
Getting "Enter passphrase to unlock /home/XXX/.aws-okta/" message when using aws-okta exec

### ISSUE THREAD

**Issue by rmanchala-conga** [segmentio/aws-okta#296]
When using aws-okta exec command I am getting this message:

"Enter passphrase to unlock /home/XXX/.aws-okta/"

I am able to press enter to by-pass the message, but sometimes I am getting this message like 4 or 5 times before executing the aws command. This is very annoying.

I have tried on Ubuntu 18.04, Ubuntu 20.04 distros running on WSL 2. All having same issue. 

Also, Tried on a regular Ubuntu VM in IBM Cloud, and ran into same issue. 

Any idea what could be causing this or how to get around this issue ?

Regards,
Raj

**Comment by nickatsegment** [comment]
Hi Raj.

FYI segmentio/aws-okta is basically shut down. https://github.com/segmentio/aws-okta/issues/278

You should try one of the other keyring backends. Depending on your OS you'll have different ones listed when you do `--help`. I'm a mac user, but `pass` is a decent Linux backend that uses gpg and so probably won't prompt as much. Good luck!
