### ISSUE TITLE
The latest release does not have built binaries for any platform

### ISSUE THREAD

**Issue by ingshtrom** [segmentio/aws-okta#301]
I know this project is on hiatus indefinitely, but I figured the CI would still work to publish binaries if a release was necessary, like the 1.0.5 was.

I see that it failed to publish binaries, but it made the release, so I'm curious if we know about this and if it will be fixed or we should expect to just build manually for our platforms now?

**Comment by ingshtrom** [comment]
For anyone seeing this later and not seeing binaries, you can clone the repo and run `make all` and then look in the `dist/` folder for the binary. Seems to work 😄 
```
⛵  docker-desktop in aws-okta on  master via 🐍 v3.8.3 (general3)
❯ make all
mkdir -p dist
GOOS=darwin GOARCH=amd64 GO111MODULE=on go build -mod=vendor -ldflags='-X "main.Version=v1.0.5"' -o dist/aws-okta-v1.0.5-darwin-amd64
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -ldflags='-X "main.Version=v1.0.5"' -o dist/aws-okta-v1.0.5-linux-amd64

⛵  docker-desktop in aws-okta/dist on  master via 🐍 v3.8.3 (general3)
❯ ./aws-okta-v1.0.5-darwin-amd64 version
aws-okta v1.0.5
```

**Comment by briantist** [comment]
At the moment, I can confirm 1.0.5 is available in brew and via apt repositories in Ubuntu

**Comment by ingshtrom** [comment]
Gotchya, I was looking at the GitHub release I guess.

**Comment by nickatsegment** [comment]
Yeah, the bot user to whom the token belongs is getting rate limited for unrelated reasons. As @briantist mentioned, the brew, debs, and RPMs are out.

There is a very good chance I'll never fix it TBH. There's no internal need for the GH releases.

**Comment by nickatsegment** [comment]
Hi folks. As of v1.0.8, I've disabled publishing to Github Releases. Given the infrequency of new releases, I decided we're just not going to fix this.

We're still publishing to [our PackageCloud](https://packagecloud.io/segment/aws-okta), which you can add as a repo or download packages from directly.

If you're looking for the unpackaged binary, you can extract it from either RPM or DEB package without too much trouble. (That's literally all there is in the package.)
