### ISSUE TITLE
AssumeRole DurationSeconds can now be up to 12 hours

### ISSUE THREAD

**Issue by hopkinsth** [segmentio/aws-okta#43]
According to AWS's documentation, `sts:AssumeRole` can return credentials that are valid up to 12 hours, so... this utility should support that behvaior: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters

Filing this in part to remind myself to submit a PR for it later.

**Comment by reverson** [comment]
I just created a PR for something unrelated, but needed to up the value to test, so I included this as part of #44. Please modify or comment if something needs to be changed.

**Comment by dfuentes** [comment]
Merged, thanks!
