### ISSUE TITLE
Support for other IdPs

### ISSUE THREAD

**Issue by wgj** [segmentio/aws-okta#47]
Is there any plans or ideas for supporting non-Okta identity providers? We're in the middle of a transition to Okta, but the project is timeline might be 12+ months. We're considering moving from IAM to Shibboleth backed federation (which is what Okta will be replacing).

**Comment by dfuentes** [comment]
No plans to support non-okta providers.  I could see our approach generalized to any SAML-based idp's, but increasing the scope in this way would be unmanageable for our small tooling team.

**Comment by wgj** [comment]
We're still discussing our level of commitment, but would you potentially be interested in a PR?

**Comment by dfuentes** [comment]
We would likely pass on such a PR.  If such a PR is easy for you all to manage, you could run a fork during the transition.
