### ISSUE TITLE
Can we use okta orgs in the okta-emea region

### ISSUE THREAD

**Issue by jschilperoord** [segmentio/aws-okta#48]
Hi,

Is it possible to use Okta organizations in the emea region? I don't see a way to provide this when executing the aws-okta add command?

Thanks,

Jeffrey

**Comment by dfuentes** [comment]
I'm not familiar with the differences for okta emea, what all needs to change?  The okta URL?

**Comment by jschilperoord** [comment]
Correct. The url ends with okta-emea.com instead of okta.com 👍

**Comment by NeuralSandwich** [comment]
I have created a merge request for this #60

**Comment by peter-murray** [comment]
I commented on the PR, but again here to ensure it is connected.

You are still excluding the Okta preview accounts with this change... if you are serious about making any change to support this properly you have to consider the preview accounts, and accounts that can operate under a custom URL, which would be a URL not using any of the three

**Comment by nickatsegment** [comment]
Fixed in #92
