### ISSUE TITLE
When I `aws-okta add` and set a password with a space character, it fails

### ISSUE THREAD

**Issue by Chili-Man** [segmentio/aws-okta#58]
I'm running Ubuntu 18.04, and am using the 0.19.0 binary that has been published here on GitHub. 

When I try running `aws-okta add`,  it always fails with the `Failed to set credentials in your keyring` when I input a password with a space character in it.  However, it works fine if the password I input does not have any space characters in it (I havent tried any other whitespace characters though).

**Comment by nickatsegment** [comment]
I'm able to repro on Mac. Will take a look

**Comment by nickatsegment** [comment]
Nope, I take that back. I cleared my keyring and now can't repro :( 

I can't repro on Linux either actually. I'm running Ubuntu 18.04 in a Docker container. I was able to add an org/user/pass that was all spaces.

If you delete `~/.aws-okta` (maybe make a backup), does it still happen?

**Comment by Chili-Man** [comment]
@nickatsegment  yeah I'm able to get it to work on the Ubuntu 18.04 container, but not with the desktop it seems.

**Comment by nickatsegment** [comment]
If you're able to build from `master`, maybe give that a go with `-d`. It'll actually log the underlying error: https://github.com/segmentio/aws-okta/blob/master/cmd/add.go#L89

**Comment by Chili-Man** [comment]
@nickatsegment  I was actually able to get a little but farther with building it from the master branch,  it asked for my MFA code this time, but still failed to set the credentials in the keyring: 

```
DEBU[0181] Failed to add user to keyring: Failed to execute program org.kde.kwalletd: No such file or directory 
Failed to set credentials in your keyring
```

**Comment by nickatsegment** [comment]
@Chili-Man I assume you don't actually want to use kwallet, right? Which backend are you using? Are you using the `--backend` flag? If you're not, try specifying it.

**Comment by Chili-Man** [comment]
@nickatsegment I was able to get it to work with the latest 0.19.4 version;  thanks for the help!
