### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by mbarany** [segmentio/aws-okta#64]
Is there a homebrew formula for this? I can't seem to find one. It would be great to have one for easy upgrading. thanks!

**Comment by boggsboggs** [comment]
Someone did kindly add it to homebrew core some time ago: https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-okta.rb

`brew install aws-okta` has historically worked for us. Segment doesn't maintain that formula though (and actually we don't know who does). There was a breaking change in the DUO api a week ago though, so until the formula is updated by our mysterious benefactor, the formula will stay broken.

**Comment by josacar** [comment]
Waiting for maintainers to check PR #70, #72 is also fixed so I'll work pushing latest release to brew https://github.com/Homebrew/homebrew-core/pull/31497
