### ISSUE TITLE
Pluggable authentication modules?

### ISSUE THREAD

**Issue by jarmbruster74** [segmentio/aws-okta#65]
I've built out a fork of this in order to integrate with a different IDP (Shibboleth) at https://github.com/CUBoulder-OIT/aws-shib

It's very raw at this point, but it makes me think there could be a good use case for making aws-okta more flexible to allow pluggable (or at least configuration driven) selection of providers.  It seems like the provider/oktaprovider relationship was built with this in mind, but right now oktaprovider is hardcoded.

I'd be happy to help with this with some PRs if there is interest in expanding aws-okta to more use cases.

**Comment by nickatsegment** [comment]
Enh, maybe? It's nice to have a focused tool though. I don't imagine there's a need for users to have a lot of IdPs, so I'm fine with forks.
