### ISSUE TITLE
The specified item could not be found in the keyring.

### ISSUE THREAD

**Issue by radding** [segmentio/aws-okta#76]
I keep getting the above error when I run `aws-okta exec`. 

This was working, until I changed my password in Okta. Then I kept getting a 401 error. I tried to figure out how to change password (because `aws-okta add` didn't work for me. So I removed the creds from Keychain, delete the application and do everything from scratch. But now I get this error. 

Version affected: `aws-okta 0.19.0` and `aws-okta dev`. I installed through homebrew and `go get`

**Comment by dfuentes** [comment]
We've seen this internally as well, quite frustrating.  Strangely, often a reboot fixes the problem (reboot, then add the new credentials with `aws-okta add`).

**Comment by radding** [comment]
I'll give that a shot.

**Comment by nickatsegment** [comment]
I've found that locking and unlocking the particular keychain will fix. A little less intrusive than a full reboot. Not sure what we can do about this though.

**Comment by mattlovenuk** [comment]
We are also seeing this issue when using it just to add to the list.

**Comment by nickatsegment** [comment]
@mattlovenuk have you had a chance to try locking and unlocking the keychain?

**Comment by mattlovenuk** [comment]
Hi, actually it has worked this time. For some reason when I tried last week it didn't work but it looks like it's OK now. Thanks.

**Comment by nickatsegment** [comment]
This came up again internally for @abraithwaite. We should probably do something about it. Locking and unlocking worked.

**Comment by injune1123** [comment]
I ran into the same issue as well, and running `aws-okta add` worked for me as well.
