### ISSUE TITLE
Support for multiple Okta tenants at once

### ISSUE THREAD

**Issue by devonbleak** [segmentio/aws-okta#91]
Would love to see support for multiple Okta tenants.

**Comment by nickatsegment** [comment]
I believe this is solved by https://github.com/segmentio/aws-okta/pull/92? Ping me if not and we can reopen

**Comment by devonbleak** [comment]
@nickatsegment updated the description to be more accurate in what I'm looking for.  We're about to be living in 2 Okta worlds at the same time :-)

**Comment by nickatsegment** [comment]
Ugh, that sounds unfun. Will reopen. Godspeed.

**Comment by LukaszRacon** [comment]
Implemented in #221
