### ISSUE TITLE
Gracefully handle requested TTL > max session duration of a role

### ISSUE THREAD

**Issue by devonbleak** [segmentio/aws-okta#95]
Currently when the requested credential TTL exceeds the max session duration allowed for the AssumeRole* call, aws-okta errors out.

I think it would be great if we could add a flag (or other mechanism) such that when this happens a warning is expressed and a second request is made with some lower TTL (1 hour?) rather than simply failing.  This would also help with "chained" AssumeRole calls which currently have a hard 1-hour max duration regardless of the max session duration of the role being assumed.

**Comment by nickatsegment** [comment]
Can you give us some examples of the before and after flows?

**Comment by devonbleak** [comment]
I'm imagining something like this:

Current:
```
$ aws-okta exec role-chain-demo -a 12h -- true     
ValidationError: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
        status code: 400, request id: 7642aa0a-e78f-11e8-8975-ab0fed969c85

$
```

Proposed (with -f/--force flag):
```
$ aws-okta exec role-chain-demo -a 12h -f -- true     
Warning: The requested DurationSeconds exceeds the limit for this operation, trying again with 1 hour duration.

$
```
There could be another error here if there's an even tighter restriction on the duration.

**Comment by nickatsegment** [comment]
One step farther though:

- `aws-okta exec -a 12h`: tells user 1h session limit, aborts
- user corrects to `aws-okta exec -a 1h`

vs 

- `aws-okta exec -a 12h`: tells user 1h session limit, aborts
- user corrects to `aws-okta exec -f`

I'm not seeing the benefit unless you just ran with `-f` all the time?

**Comment by devonbleak** [comment]
I'm only proposing the -f if we're tied to keeping the existing functionality where we error out with duration > max for that operation.  Tbh I'd prefer to just update the default behavior to be the warning/retry flow but some projects don't like changing existing behaviors like that.

**Comment by nickatsegment** [comment]
Maybe we could introduce a per-profile option that enables that behavior?

I suspect changing the default behavior would be surprising to some users, but I don't have a good feel for that.

**Comment by devonbleak** [comment]
That could work, maybe along with an environment variable.  I generate my AWS config so it's easy to add something like that to every profile but an env var would make it easy for others to make it their default also.

**Comment by jspiro** [comment]
+1
